name: "Build and Deploy to Cloudflare Pages"
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Godot
        uses: chickensoft-games/setup-godot@v2
        with:
          version: 4.5.0
          use-dotnet: false
          include-templates: true

      - name: Export Web
        run: godot --headless --export-release "Web" build/web/index.html

      - name: Deploy to itch.io
        uses: Ayowel/butler-to-itch@v1.3.0
        with:
          butler_key: ${{ secrets.ITCHIO_API_KEY }}
          itch_user: ${{ vars.ITCH_USERNAME }}
          itch_game: ${{ vars.ITCH_GAME_ID }}
          version: ${{ github.sha }}
          files: |
            html5 build/web
